### ISSUE TITLE
is it possible to manage several backuppc servers?

### ISSUE THREAD

**Issue by hpkunz** [treydock/puppet-backuppc#3]
Hi there,

your module looks interesting. we have several backuppc servers. is it possible to control which client is backed up on which backuppc server?

best,
Hp

**Comment by treydock** [comment]
The clients associated with a given BackupPC server are done through exported resource tags.

The server collects based on it's FQDN and the client must set:

```
backuppc::client::backuppc_hostname: backuppc1.example.com
```

The above would set it so that the client with that would go to backuppc1.example.com host based on that server's FQDN.
